import 'dart:async';
import 'dart:math';

import 'package:flutter/foundation.dart';
import 'package:ledfx/src/core.dart';
import 'package:ledfx/src/devices/device.dart' show Device;
import 'package:ledfx/src/audio/const.dart';
import 'package:ledfx/src/effects/effect.dart';
import 'package:ledfx/utils/utils.dart';
import 'package:nanoid/nanoid.dart';

enum TransitionMode { add }

class VirtualConfig {
  String name;
  String deviceID;
  bool autoGenerated;
  int minFreq;
  int maxFreq;
  String segmentMapping;
  int? grouping;
  double maxBrightness;
  int centerOffset;
  bool previewOnly;
  double transitionTime;
  TransitionMode transitionMode;
  int rows;
  VirtualConfig({
    required this.name,
    required this.deviceID,
    required this.autoGenerated,
    this.minFreq = MIN_FREQ,
    this.maxFreq = MAX_FREQ,
    this.segmentMapping = "span", // span | copy
    this.grouping,
    this.maxBrightness = 1.0,
    this.centerOffset = 1,
    this.previewOnly = false,
    this.transitionTime = 0.4,
    this.transitionMode = TransitionMode.add,
    this.rows = 1,
  });

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'deviceID': deviceID,
      'autoGenerated': autoGenerated,
      'minFreq': minFreq,
      'maxFreq': maxFreq,
      'mapping': segmentMapping,
      'grouping': grouping,
      'maxBrightness': maxBrightness,
      'centerOffset': centerOffset,
      'previewOnly': previewOnly,
      'transitionTime': transitionTime,
      'transitionMode': transitionMode.name,
      'rows': rows,
    };
  }

  factory VirtualConfig.fromJson(Map<String, dynamic> json) {
    return VirtualConfig(
      name: json['name'],
      deviceID: json['deviceID'],
      autoGenerated: json['autoGenerated'],
      minFreq: json['minFreq'] ?? MIN_FREQ,
      maxFreq: json['maxFreq'] ?? MAX_FREQ,
      segmentMapping: json['mapping'] ?? "span",
      grouping: json['grouping'],
      maxBrightness: json['maxBrightness'] ?? 1.0,
      centerOffset: json['centerOffset'] ?? 1,
      previewOnly: json['previewOnly'] ?? false,
      transitionTime: json['transitionTime'] ?? 0.4,
      transitionMode: json['transitionMode'] != null
          ? TransitionMode.values.firstWhere((e) => e.name == json['transitionMode'])
          : TransitionMode.add,
      rows: json['rows'] ?? 1,
    );
  }
}

class SegmentConfig {
  final String deviceID;
  final int start;
  final int end;
  final bool inverted;
  SegmentConfig(this.deviceID, this.start, this.end, this.inverted);

  Map<String, dynamic> toJson() {
    return {'deviceID': deviceID, 'start': start, 'end': end, 'inverted': inverted};
  }

  factory SegmentConfig.fromJson(Map<String, dynamic> json) {
    return SegmentConfig(json['deviceID'], json['start'], json['end'], json['inverted']);
  }
}

class Virtual {
  Virtual({required this.id, required VirtualConfig config, required this.ledfx}) {
    _config = config;
    freqRange = (config.minFreq, config.maxFreq);
  }

  final String id;
  final LEDFx ledfx;
  late VirtualConfig _config;
  VirtualConfig get config => _config;
  set config(VirtualConfig newConfig) {
    final oldConfig = config;
    _config = newConfig;

    bool effectReactivate = false;
    if (config.segmentMapping != oldConfig.segmentMapping) {
      invalidateCache();
      effectReactivate = true;
    }
    if (config.transitionMode != oldConfig.transitionMode || config.transitionTime != oldConfig.transitionTime) {
      // TODO: Set Frame Transition
    }
    // TODO: Freqency related updates

    if (effectReactivate) {
      reactivateEffect();
    }
  }

  void updateConfig(VirtualConfig config) {
    this.config = config;
  }

  String get name => config.name;
  String get deviceID => config.deviceID;
  bool get autoGenerated => config.autoGenerated;
  int get rows => config.rows;
  set rows(r) {
    config.rows = max(1, r);
  }

  bool _paused = false;
  bool get paused => _paused;

  bool _streaming = false;
  bool get streaming => _streaming;

  Effect? _activeEffect;
  Effect? get activeEffect => _activeEffect;

  late (int, int) freqRange;

  List<Device>? _cachedDevices;
  List<Device> get devices => () {
    if (_cachedDevices != null) return _cachedDevices!;
    final devs = <Device>[];
    for (var s in segments) {
      if (ledfx.devices.devices[s.deviceID] != null) {
        devs.add(ledfx.devices.devices[s.deviceID]!);
      }
    }
    _cachedDevices = devs;
    return _cachedDevices!;
  }();

  final List _oneshots = [];
  List get oneshots => _oneshots;

  // This Controls Activation - Deactivation of the virtual
  // set the value to true/false instead of directly calling activate() or deactivate()
  bool _isActive = false;
  bool get isActive => _isActive;
  set isActive(param) {
    (param && !_isActive) ? activate() : deactivate();
    _isActive = param;
  }

  int? _cachedRefreshRate;
  int get refreshRate => () {
    if (_cachedRefreshRate != null) return _cachedRefreshRate!;
    if (devices.isEmpty) return 0;
    _cachedRefreshRate = devices.fold<int>(360, (p, d) {
      return min(p, d.maxRefreshRate);
    });
    return _cachedRefreshRate!;
  }();

  // Activates and starts the render loop
  Timer? _frameTimer;
  double _frameInterval = 0.001; // Calculated sleep time
  double fpsToSleepInterval(int fps) => max(0.001, 1 / fps);
  void activate() {
    if (devices.isEmpty) {
      debugPrint("no devices setup");
      return;
    }
    if (activeEffect == null) {
      debugPrint("no effect configured");
      return;
    }

    debugPrint("Virtual $id: Activating with segments $segments");

    if (!_isActive) {
      _isActive = true;
      try {
        activateSegments(segments);
      } on ArgumentError catch (e) {
        debugPrint(e.toString());
      }
    }
    // Calculate the base interval needed for the desired FPS
    _frameInterval = fpsToSleepInterval(refreshRate);
    debugPrint("STARTING VIRTUAL RENDER LOOP | virtual: $id | fps: $refreshRate | interval: $_frameInterval");
    _frameTimer = Timer.periodic(Duration(milliseconds: (_frameInterval * 1000).round()), _renderLoop);
  }

  void _renderLoop(Timer timer) {
    if (!_isActive) {
      timer.cancel();
      return;
    }

    // final startTime = DateTime.now().microsecondsSinceEpoch;

    if (activeEffect != null && activeEffect!.isActive && activeEffect!.pixels != null) {
      _cachedAssembledFrame = assembleFrame();
      if (_cachedAssembledFrame != null && !paused) {
        if (!config.previewOnly) {
          flush();
        }
        // TODO: fire Virtual Pixels for Visualizer Preview
        // ledfx.sendVirtualPixelsToUI(_cachedAssembledFrame!);
      }
    }

    // --- Frame Rate Adjustment (Replacing time.sleep) ---

    // 4. Calculate actual runtime and adjust for the next frame.
    // final double runTimeSeconds =
    //     (DateTime.now().microsecondsSinceEpoch - startTime) / 1000000.0;

    // // Calculate required sleep time
    // double sleepTimeSeconds = max(0.001, _frameInterval - runTimeSeconds);

    // If timing must be precise, cancel and reschedule the timer.
    /*
    timer.cancel();
    _frameTimer = Timer(Duration(milliseconds: (sleepTimeSeconds * 1000).round()), () {
        // Run the logic again
        _threadFunction(timer); 
    });
    */
  }

  /// Assembled Frame List with each representing a row in the virtual
  /// each Uint8List is a pixel with 3 bytes (R, G, B)
  List<Uint8List>? _cachedAssembledFrame;
  List<Uint8List>? assembleFrame() {
    activeEffect?.render();
    return activeEffect?.getPixels();
  }

  final bool _calibration = false;
  // Flushes the assembled frame to the devices
  void flush([List<Uint8List>? pixels]) {
    pixels = pixels ?? _cachedAssembledFrame;
    if (pixels == null) return;

    // segment - Virtual Start, Virtual End, Virtual Step, Device Start, Device End
    segmentsByDevice.forEach((deviceID, segments) {
      var data = <(List<Uint8List>, int, int)>[];
      final device = ledfx.devices.devices[deviceID];

      if (device != null && device.isActive) {
        if (_calibration) {
          // renderCalibration(data, device, segments, deviceID);
        } else if (config.segmentMapping == "span") {
          // span - the pixel strip are sliced to all segments
          pixels = effectiveToPhysicalPixels(pixels!);

          for (final (vStart, vStop, step, devStart, devEnd) in segments) {
            final seg = pixels!.slice(start: vStart, stop: vStop, step: step);
            data.add((seg, devStart, devEnd));
          }
        } else if (config.segmentMapping == "copy") {
          // copy - each segment has same pixels SCALED to length
          for (final (vStart, vStop, step, devStart, devEnd) in segments) {
            final targetPhysicalLen = devEnd - devStart + 1;
            final targetEffectLen = _getEffectivePixelCount(targetPhysicalLen);
            var seg = interpolatePixels(pixels!, targetEffectLen, step);
            seg = effectiveToPhysicalPixels(seg, targetEffectLen);
            data.add((seg, devStart, devEnd));
          }
        }
        device.updatePixels(id, data);
      }
    });
  }

  /// Segments of the Virtual - Represents the mapping of the virtual to the devices
  /// components - deviceID, start, end, inverted segment or not
  List<SegmentConfig> segments = [];

  Map<String, List<(int, int, int, int, int)>>? _cachedSegmentByDevice;

  /// Calculated once on first access and cached ↑
  /// sorted Map of deviceID: - List of (start, stop, step, segment_start, segment_end) for easy access
  /// also maps all segments in single strip in order.
  /// start, stop - start and stop indices of the segment in the virtual
  /// step - step of the segment in the virtual
  /// segment_start, segment_end - start and stop indices of the segment in the device
  Map<String, List<(int, int, int, int, int)>> get segmentsByDevice => () {
    if (_cachedSegmentByDevice != null) return _cachedSegmentByDevice!;
    int dataStart = 0;
    final Map<String, List<(int, int, int, int, int)>> segmentsByDevice = {};
    for (var s in segments) {
      final segWidth = s.end - s.start + 1;
      int start, stop, step = 0;
      if (!s.inverted) {
        start = dataStart;
        stop = dataStart + segWidth;
        step = 1;
      } else {
        start = dataStart + segWidth - 1;
        stop = (dataStart == 0) ? 0 : dataStart - 1;
        step = -1;
      }

      final segmentInfo = (start, stop, step, s.start, s.end);
      if (segmentsByDevice.containsKey(s.deviceID)) {
        segmentsByDevice[s.deviceID]!.add(segmentInfo);
      } else {
        segmentsByDevice[s.deviceID] = [segmentInfo];
      }

      dataStart += segWidth;
    }
    _cachedSegmentByDevice = segmentsByDevice;
    return _cachedSegmentByDevice!;
  }();

  int? _cachedPixelCount;
  int get pixelCount => () {
    if (_cachedPixelCount != null) return _cachedPixelCount!;
    if (config.segmentMapping == "span") {
      int total = 0;
      for (var s in segments) {
        total += (s.end - s.start + 1);
      }
      _cachedPixelCount = total;
    } else if (config.segmentMapping == "copy") {
      if (segments.isNotEmpty) {
        _cachedPixelCount = segments.fold<int>(0, (p, s) {
          return max(p, (s.end - s.start + 1));
        });
      } else {
        _cachedPixelCount = 0;
      }
    } else {
      _cachedPixelCount = 0;
    }
    return _cachedPixelCount!;
  }();

  int _getEffectivePixelCount(int physicalPixelCount) {
    return (physicalPixelCount / groupSize).ceil();
  }

  int? _cachedEffectivePixelCount;
  int get effectivePixelCount => () {
    if (_cachedEffectivePixelCount != null) return _cachedEffectivePixelCount!;
    _cachedEffectivePixelCount = _getEffectivePixelCount(pixelCount);
    return _cachedEffectivePixelCount!;
  }();

  int? _cachedGroupSize;
  int get groupSize => () {
    if (_cachedGroupSize != null) return _cachedGroupSize!;
    _cachedGroupSize = (config.grouping == null || config.grouping! < 1) ? 1 : config.grouping;
    return _cachedGroupSize!;
  }();

  List<Uint8List> effectiveToPhysicalPixels(List<Uint8List> effectivePixels, [int? pixelCount]) {
    if (groupSize <= 1) return effectivePixels;
    pixelCount = pixelCount ?? this.pixelCount;

    effectivePixels = repeatAndTruncatePixels(effectivePixels, groupSize, pixelCount);

    return effectivePixels;
  }

  void setEffect(Map<String, dynamic> effectData, [double? fallback]) {
    if (devices.isEmpty) {
      debugPrint("can not set effect, no active device");
    }

    isActive = false;

    final effect = ledfx.effects.create(effectData);

    if (fallback != null) {}

    clearActiveEffect();
    _activeEffect = effect;
    _activeEffect!.activate(this);
    // TODO:
    // ledfx.events.fireEvent(EffectSetEvent);

    try {
      isActive = true;
    } catch (e) {
      isActive = false;
      debugPrint(e.toString());
    }
  }

  // deactivates and stops the render loop along with reset timer
  void deactivate() {
    _isActive = false;
    _frameTimer?.cancel();
    _frameTimer = null;

    deactivateSegments();
    ledfx.updateCoreConfig();
    ledfx.virtuals.checkAndDeactivateDevices();
  }

  // deactivate virtual during removal
  void remove() {
    _isActive = false;
  }

  void reactivateEffect() {
    if (activeEffect != null) {
      activeEffect!.deactivate();
      if (pixelCount > 0) {
        activeEffect!.activate(this);
      }
    }
  }

  void updateSegments(List<SegmentConfig> segments) {
    final pCount = pixelCount;

    List<SegmentConfig> validatedSegments = [];
    for (var s in segments) {
      validatedSegments.add(validateSegment(s));
    }

    if (isActive) {
      deactivateSegments();
      try {
        activateSegments(validatedSegments);
      } catch (e) {
        deactivateSegments();
        activateSegments(this.segments);
        rethrow;
      }
    }

    this.segments = validatedSegments;
    invalidateCache();

    // restart effect if pixel count changes
    if (pixelCount != pCount) {
      reactivateEffect();
    }

    ledfx.virtuals.checkAndDeactivateDevices();
  }

  SegmentConfig validateSegment(SegmentConfig segment) {
    final device = ledfx.devices.devices[segment.deviceID];
    if (device == null) {
      throw Exception("Invalid DeviceID - ${segment.deviceID}");
    } else if (segment.start < 0 ||
        segment.end < 0 ||
        segment.start > segment.end ||
        segment.start >= device.pixelCount ||
        segment.end >= device.pixelCount) {
      debugPrint(
        "Invalid segment pixels in Virtual '${config.name}': segment('${device.name}' (${segment.start}, ${segment.end})) valid pixels between (0, ${device.pixelCount - 1})",
      );

      int start = 0;
      int end = 0;
      if (segment.start < 0) start = 0;
      if (segment.end < 0) end = 0;
      if (segment.start > segment.end) start = end;
      if (segment.start >= device.pixelCount) start = device.pixelCount - 1;
      if (segment.end >= device.pixelCount) end = device.pixelCount - 1;

      return SegmentConfig(segment.deviceID, start, end, segment.inverted);
    }
    return segment;
  }

  void activateSegments(List<SegmentConfig> segments) {
    for (var config in segments) {
      final device = ledfx.devices.get(config.deviceID);
      if (device == null) continue;
      if (!device.isActive) device.activate();
      device.addSegment(SegmentConfig(id, config.start, config.end, config.inverted), true);
    }
  }

  void deactivateSegments() {
    for (var device in devices) {
      device.clearVirtualSegments(id);
    }
  }

  void invalidateCache() {
    _cachedPixelCount = null;
    _cachedRefreshRate = null;
    _cachedDevices = null;
    _cachedSegmentByDevice = null;
    _cachedEffectivePixelCount = null;
    _cachedGroupSize = null;
  }

  void clearEffect() {
    clearActiveEffect();
    ledfx.updateCoreConfig();
  }

  void clearActiveEffect() {
    if (_activeEffect != null) {
      _activeEffect!.deactivate();
      _activeEffect = null;
    }
  }
}

class Virtuals with Iterable<MapEntry<String, Virtual>> {
  // Singleton instance
  static Virtuals? _instance;

  factory Virtuals({required LEDFx ledfx}) {
    _instance ??= Virtuals._(ledfx: ledfx);
    return _instance!;
  }

  Virtuals._({required this.ledfx}) {
    _paused = false;
    virtuals = {};
  }

  LEDFx ledfx;
  late bool _paused;

  // Store all virtuals
  Map<String, Virtual> virtuals = {};
  @override
  Iterator<MapEntry<String, Virtual>> get iterator => virtuals.entries.iterator;
  Virtual? get(String id) => virtuals[id];

  // resets this singleton with new LEDFx core
  void resetForCore(LEDFx ledfx) {
    this.ledfx = ledfx;
    if (virtuals.isNotEmpty) {
      virtuals.clear();
    }
    _paused = false;
  }

  // Populate Virtuals from core config - usually called during initiation of core
  void createFromConfig(List<Map<String, dynamic>> config, bool pauseAll) {
    if (config.isEmpty) return;

    for (final virtualData in config) {
      final virtualId = virtualData['id'];
      final configMap = virtualData['config'] as Map<String, dynamic>;
      final vConfig = VirtualConfig.fromJson(configMap);
      final active = virtualData['active'];
      final effectData = virtualData['activeEffect'];
      final segmentsList = virtualData['segments'] as List<dynamic>?;

      final virtual = create(virtualId, vConfig);

      if (segmentsList != null && segmentsList.isNotEmpty) {
        final segments = segmentsList.map((s) => SegmentConfig.fromJson(s as Map<String, dynamic>)).toList();
        virtual.updateSegments(segments);
      }

      if (effectData != null) {
        virtual.setEffect(effectData);
      }

      if (!active) virtual.isActive = false;

      if (pauseAll) virtual._paused = true;
    }
  }

  // Creates a new blank virtual strip with given name and default values
  Future<void> addNewVirtual(String name) async {
    try {
      create(nanoid(10), VirtualConfig(name: name, deviceID: "", rows: 0, autoGenerated: false));
    } catch (e) {
      debugPrint("Failed to Create Virtual Strip: $e");
      rethrow;
    }
  }

  // Create and add Virtual to registry and returns the Virtual instance
  Virtual create(String id, VirtualConfig config) {
    final v = Virtual(id: id, config: config, ledfx: ledfx);
    virtuals[id] = v;
    return v;
  }

  //  removes the virtual [id] from registry
  removeVirtual(String id) {
    if (!virtuals.keys.contains(id)) return;
    virtuals[id]!.remove();
    virtuals.removeWhere((k, _) => k == id);
  }

  // pause all virtual
  void pauseAll() {
    _paused = true;
    for (final v in virtuals.values) {
      v._paused = _paused;
    }
  }

  //   Checks all active virtuals and segments to compile a list of active devices,
  // then deactivates any active devices not in that list.

  // This process ensures that devices are only deactivated if no virtual or segment
  // is using them, which is especially relevant during virtual or segment deactivation
  // or reconfiguration.

  // It also walks through all virtuals, if they are in the active devices list, but not active, they will be marked as streaming

  // Note: This is a relatively expensive operation but only runs when a virtual
  // is deactivated or segments are modified.
  void checkAndDeactivateDevices() {
    Set activeDevices = <String>{};

    for (final virtual in virtuals.values) {
      if (virtual.isActive) {
        for (final s in virtual.segments) {
          activeDevices.add(s.deviceID);
        }
      }
    }

    for (final dev in ledfx.devices.devices.values) {
      if (!activeDevices.contains(dev.id) && dev.isActive) {
        dev.deactivate();
      }
    }

    for (final vid in ledfx.virtuals.virtuals.keys) {
      final v = ledfx.virtuals.virtuals[vid];
      v!._streaming = (activeDevices.contains(vid) && !v.isActive);
    }

    debugPrint("active devices - ${activeDevices.toString()}");
  }
}
